name: Do cloc

on:
    push:
        branches:
            - develop
    
jobs:
    run-cloc:
        name: Run cloc
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Setup cloc
              run: sudo apt install cloc
            - name: Run cloc
              run: cloc . --by-file --csv --include-ext=py --exclude-dir=tests,tools --not-match-f='__init__.py' --report-file="stepcount_dummy.csv"
            - name: Upload cloc result
              uses: actions/upload-artifact@v2
              with:
                name: result
                path: stepcount_dummy.csv