name: Do lint # ワークフロー名

on: # 起動トリガ
  pull_request: # PRで発火
    types: [opened, synchronize] # PRの新規作成、更新時に発火。

jobs: # 処理内容
  run-lint:
    name: Run Lint
    runs-on: ubuntu-latest # 実行環境指定
    strategy:
      matrix:
        python-version: [3.12.6] # pythonバージョンを指定
    steps:
      - name: Checkout Repository # リポジトリのチェックアウト
        uses: actions/checkout@v4 # GitHubリポジトリからコードをチェックアウト
      - name: Set up Python ${{ matrix.python-version }} # Python環境のセットアップ
        uses: actions/setup-python@v4 # Python環境のセットアップアクションを使用
        with:
          python-version: ${{ matrix.python-version }} # マトリクスで指定されたPythonバージョンを使用
      - name: Install Poetry # Poetryのインストール
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Export requirements.txt # requirements.txtの作成
        run: poetry export -f requirements.txt -o requirements.txt --without-hashes --with dev
      - name: Install Dependencies # 依存関係のインストール
        run: pip install -r requirements.txt  # pyproject.tomlから依存関係をインストール
      - name: Run Lint
        run: ruff check . --output-format=github --config=pyproject.toml