name: Do pytest # ワークフローの名前を指定

on: # トリガー条件を指定
  pull_request: # プルリクエストに反応
    types: [opened, synchronize] # プルリクエストがオープン、更新された場合にトリガー

jobs: # ジョブの定義を開始
  pytest: # ジョブ名を指定
    name: pytest # ジョブの名前
    runs-on: ubuntu-latest # Ubuntu Linux 上で実行
    steps: # ジョブ内のステップの定義を開始
      - name: Checkout Repository # リポジトリのチェックアウト
        uses: actions/checkout@v4 # GitHubリポジトリからコードをチェックアウト
      - name: Set up Python ${{ matrix.python-version }} # Python環境のセットアップ
        uses: actions/setup-python@v4 # Python環境のセットアップアクションを使用
        with:
          python-version-file: ".python-version" # 開発環境で使用しているPythonバージョンを使用
      - name: Install Poetry # Poetryのインストール
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Export requirements.txt # requirements.txtの作成
        run: poetry export -f requirements.txt -o requirements.txt --without-hashes --with dev
      - name: Install Dependencies # 依存関係のインストール
        run: pip install -r requirements.txt  # pyproject.tomlから依存関係をインストール
      - name: Run pytest
        run: pytest  # pytestを実行
